### ISSUE TITLE
Arrow keys escape modal

### ISSUE THREAD

**Issue by iamjolly** [svinkle/launchy#13]
Launchy is a super-cool demo. Thanks for making it!

One thing I've noticed with many accessible modal examples (and ones in production, too) is that keyboard focus is trapped well for the `[tab]` key. But, when navigating using arrow keys, like to read the contents of the modal line-by-line, you can inadvertently escape the modal window and find yourself on the underlying page. This behavior seems consistent across all the major browser/AT combinations. 

Maybe this is a known issue that can't really be handled well, but I thought I'd raise it for discussion and investigation. 

Here's a screenshot showing Safari/VO with focus outside the open modal after using arrow keys.
![screenshot 2017-08-22 15 48 31](https://user-images.githubusercontent.com/1093423/29589366-332c47be-8752-11e7-9318-d4500edab3f9.png)

**Comment by svinkle** [comment]
Totally! I know exactly what you mean. I've noticed the same thing myself when using VO cursor to move around the content of modal windows. I'm really not sure what the answer would be, as like you said, it's a consistent behaviour experienced across the board.

I'm going to bring this question back to the @simplyaccessible team to see if we've done any testing or have any notes regarding this behaviour. Very curious now.

Thanks for checking it out and for the kind words!

Uhg, still need to fix the default styling for Safari; really doesn't like the flexbox treatment for some reason.

**Comment by svinkle** [comment]
@iamjolly So I found out that there are techniques you can add to your HTML to prevent this behaviour! A comment from my colleague, @joe-watkins:

> I’d recommend a container around content you don’t want access to with `aria-hidden="true"`, `tabindex="-1"`, and maybe an `inert` attribute. This would require that the modal fall outside of such container when the modal is active.

So basically, make everything else on the page hidden from assistive technology. I'm still sorting it all out, trying to apply it to Launchy here in some manner, but there's something to go with now. 🙂

**Comment by scottaohara** [comment]
I've solved this in my modal script by wrapping the contents of `<body>` in a new `<div>` with a new unique ID.

Then I position the modal(s) outside of the new wrapper, so on launch I can hide the contents of the document, sans modals.

It feels like a hack (cause it is) but I have yet to find a better (browser supported) solution that will mitigate screen readers from being able to bust out of the modals.

**Comment by svinkle** [comment]
Just thinking about how to address this. 

I had the same thought, add all elements as children to a new `div`, set the modal and overlay as siblings to this new `div`. I wonder if there's any perf drawback to this; moving all the things into then back out of a container? Then there's also the potential for something to break. If a site has JS or CSS that's been over engineered, relying on the current placement of things in the DOM…

The other thought I have is utilizing the [focusable](https://www.npmjs.com/package/focusable) package that I'm using as a dep. On `showModal()`, select all focusable elements and add `tabindex="-1"` and `aria-hidden="true"`. Remove these attributes on `hideModal()`.

Either way, feels like a hack and I don't like that feeling. Something needs to be done, though, cause the current usability is not great as a result. 🤔

**Comment by svinkle** [comment]
I think this might be fixed. @iamjolly, try out the demo page now and see how it goes. https://svinkle.github.io/launchy/

@scottaohara I went with my second thought outline above. I think the code makes sense? I really wish I had more tests. 😬

Check it out, see what you think. https://github.com/svinkle/launchy/commit/455c56c052a12136540df91a033dfb9647723fc0

Either way, just released [v0.7.0](https://github.com/svinkle/launchy/releases/tag/v0.7.0).

**Comment by iamjolly** [comment]
Thank you Scott and Scott! 

I didn't dig into the code itself yet, just tested with Safari+VO. 

It seems I can break out of the modal by using arrows to read each line and it continues on to the GitHub and Twitter elements in the underlying page. Here's a quick screencast of that action: https://www.dropbox.com/s/dqksdiqy42so46p/launchy-escape-sequence.mp4?dl=0

**Comment by svinkle** [comment]
@iamjolly, thanks for making the video! I also noticed this, specifically when using the up and down arrows.

It's different when using, what I call, the VO cursor. That is, when navigating using `Ctrl` + `Opt` + `arrow` keys. Navigation in this manner does not leave the window, as seen when tabbing.

I'm no VO pro or anything, but it does seem odd that VO would still focus on items that have `aria-hidden="true"` && `tabindex="-1"` applied. Perhaps when the page loads it caches the elements somehow? It might keep a record of focusable elements even though the ones behind the window are technically not available? I'm probably making stuff up at this point.

I'll have to do some research into what VO is actually doing when navigating via only arrow keys cause this is really strange. 🤔

**Comment by iamjolly** [comment]
Tomorrow I can do a couple of tests with NVDA and JAWS and see if they have similar outcomes. Either way, I don't think any of this is show-stopping and you have a really graceful way of handling interaction in this modal. So, thank you!!

**Comment by scottaohara** [comment]
FWIW this shouldn't be the case anymore with Safari 12 + VO 9 on macOS.

**Comment by iamjolly** [comment]
Yep. This is no longer an issue with latest Safari and VO. Closing and backing away slowly. Hope everyone is as well as can be during these trying times.
