### ISSUE TITLE
Demo link redirecting

### ISSUE THREAD

**Issue by iamjolly** [svinkle/launchy#14]
Hey Scott,

I just noticed the demo link redirects from GH Pages to your parked domain page. Weird, right?

```
 ✘ ★   ~   curl -s -D - svinkle.github.io/launchy/ -o /dev/null
HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Content-Type: text/html
Location: http://svinkle.me/launchy/
X-GitHub-Request-Id: 70B2:6CC2:7D6BD8:AFB550:59A841EF
Content-Length: 178
Accept-Ranges: bytes
Date: Thu, 31 Aug 2017 17:05:51 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-den6021-DEN
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1504199152.504467,VS0,VE58
Vary: Accept-Encoding
X-Fastly-Request-ID: ae586c2aa5e89e1797291cbc40c17ef04fd79c25
```

**Comment by svinkle** [comment]
Hmm, I was worried about this. I've never had much luck with custom domain names and `gh-pages` + Hover.com. It's working for me just fine; perhaps I should wait to see if it's just a global/area specific DNS thing?

If you could try it again in 24 hours and it's still not redirecting I'll just remove the custom domain.

Thank for letting me know, @iamjolly.

**Comment by iamjolly** [comment]
It started working a couple hours ago for me too. Then I figured out it was probably DNS. Closing!

**Comment by svinkle** [comment]
It's not just you @iamjolly (down for me atm.) I've reached out to Hover about this. I've tried other tld's with their service with `gh-pages` and it's so spotty; just up and down. I'll probably just remove the domain and get a refund if I don't hear back.

**Comment by svinkle** [comment]
So, lesson learned:

1. Reach out to support sooner, **don't assume** it's _their_ fault
2. **Remove** default domain registrar DNS records so that your domain's DNS _doesn't_ point to **two things at the same time** 🙈

(DNS had entries for parked page **&&** GitHub…)
