### ISSUE TITLE
Add inert

### ISSUE THREAD

**Issue by svinkle** [svinkle/launchy#15]
Import the [`inert` polyfill](https://github.com/WICG/inert). Will enable the removal of a bunch of code and greatly simply things.

Example: https://github.com/alexcarpenter/butane-sidenav/blob/master/src/main.js

**Comment by adrichey** [comment]
Is there anything else you need besides just importing the polyfill and adding it to the dependencies?

**Comment by svinkle** [comment]
@adrichey Thanks for looking into this!

I think besides getting the polyfill in and making sure to use it when appropriate (on `showModal()`) you could also remove a bunch of code. I recently added some code that mimics the inert state for all other elements on the page. Basically the `prepareFocusable()`, `inertElements()` methods and `data-launchy-focusable` related code could be removed.

**Comment by adrichey** [comment]
@svinkle I got busy at work and as a result, my coding free time hasn't been what I would have liked it to be recently. I just submitted https://github.com/svinkle/launchy/pull/21. I was only able to get inert installed as a dependency and refactor `inertElements()` to use it. Sorry for the delay and that I couldn't get more done on this.

**Comment by svinkle** [comment]
@adrichey All good! These things happen. Thanks for your contribution! I'll give this a look over tomorrow and get it merged in.

**Comment by adrichey** [comment]
Glad I could assist! 😄
