### ISSUE TITLE
Help with Codecov

### ISSUE THREAD

**Issue by svinkle** [svinkle/launchy#17]
I recently implemented [Codecov](https://codecov.io) reporting for test coverage. The problem is that [Codecov is reporting 100% coverage](https://codecov.io/gh/svinkle/launchy) which I _know_ is not at all accurate!

**Do you have any experience in setting this up properly?**

Check out the current configuration between the [karma.conf.js](https://github.com/svinkle/launchy/blob/master/karma.conf.js) file and [package.json](https://github.com/svinkle/launchy/blob/master/package.json). See anything fishy there? Let me know and/or create a PR with a fix! 😀

**Comment by rareinator** [comment]
Would love to take a look, haven't worked that much with Codecov though, but two pair of eyes are always better then one. 😀

**Comment by svinkle** [comment]
Awesome, thanks @Rarer! I'm going to have another look later on.
