### ISSUE TITLE
Make sure build is run before commit

### ISSUE THREAD

**Issue by svinkle** [svinkle/launchy#3]
…otherwise there could be commits of the dev build. Maybe [precommit](https://www.npmjs.com/package/precommit)?

**Comment by alexcarpenter** [comment]
I'd recommend checking out https://github.com/typicode/husky Really easy to implement.

**Comment by svinkle** [comment]
@alexcarpenter Thanks for the link! I'll check this out.

**Comment by svinkle** [comment]
@alexcarpenter Works like a charm! I added this to `package.json`:
```
"precommit": "npm test && npm run build && git add .",
```
Thanks for the tip!
