### ISSUE TITLE
Should this use a dialog element?

### ISSUE THREAD

**Issue by svinkle** [svinkle/launchy#5]
Question from Twitter:

> Wouldn't it be okay to use dialog and treating as div?

https://twitter.com/knowkalpesh/status/892070583692795904

Investigate!

**Comment by weboverhauls** [comment]
Sadly, the dialog element is at risk in HTML5.2. Under "Status of this document": https://www.w3.org/TR/html52/

**Comment by svinkle** [comment]
Wow! I did _not_ know this. Would this be a result of low adoption? And low adoption being a result of low support and limited styling? Thanks for sharing, @weboverhauls!
