### ISSUE TITLE
Make dependencies, devDependencies

### ISSUE THREAD

**Issue by alexcarpenter** [svinkle/launchy#7]
Since you are generating the dist file for NPM I would recommend updating your dependencies to be devDependencies.

![screen shot 2017-08-01 at 8 59 40 am](https://user-images.githubusercontent.com/825855/28826341-c8dc3d26-7697-11e7-9c9c-5a4603f95edb.jpg)

Reference: https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies#22004559

**Comment by svinkle** [comment]
@alexcarpenter Good tip, though isn't the "new way" to install `npm` packages is to use `npm i package`? I thought they were doing away with `devDependencies`? I could be mistaken.

Either way, I should change this up.
